import type { Section21FormData } from "@/lib/documents/section-21/schema";

export function buildSection21Prompt(data: Section21FormData): string {
  const propertyAddress = [
    data.propertyAddressLine1,
    data.propertyAddressLine2,
    data.city,
    data.postcode,
  ]
    .filter(Boolean)
    .join(", ");

  const tenants = data.tenantNames.filter(Boolean).join(", ");

  return `You are drafting a Section 21 notice template for a private residential tenancy in England or Wales.

Use ONLY the facts provided. Do not invent dates, names, or legal grounds. Use formal but plain English suitable for a landlord serving notice on a tenant.

Facts:
- Landlord name: ${data.landlordName}
- Landlord address: ${data.landlordAddress}
- Property address: ${propertyAddress}
- Tenant name(s): ${tenants}
- Tenancy start date: ${data.tenancyStartDate}
- Monthly rent: £${data.rentAmount.toFixed(2)}
- Deposit protection scheme: ${data.depositScheme || "Not specified"}
- Date possession is required: ${data.possessionDate}

Return JSON matching this schema:
{
  "title": "Section 21(1)(b) Notice Requiring Possession",
  "sections": [
    { "heading": "optional section heading", "paragraphs": ["paragraph text"] }
  ],
  "disclaimer": "This document was generated by LetLogic and is not legal advice. The landlord should verify all details and seek legal advice for complex cases.",
  "generatedAt": "ISO date string for today"
}

Include standard Section 21 elements: parties, property address, statement that the landlord requires possession, the date after which proceedings may be begun, and information about the tenant's rights. Note that minimum notice periods apply and the landlord must comply with all legal requirements.`;
}
