import Link from "next/link";
import { LegalPage } from "@/components/layout/legal-page";
import { site } from "@/lib/site";

export const metadata = {
  title: "Terms of Service",
  description:
    "The terms governing your use of the LetLogic tenant-screening service.",
};

export default function TermsPage() {
  return (
    <LegalPage
      title="Terms of Service"
      intro="The agreement between you and LetLogic when you use the service."
    >
      <p>
        These Terms of Service (&ldquo;Terms&rdquo;) govern your use of the{" "}
        {site.name} tenant-screening service provided by{" "}
        {site.company.legalName} (&ldquo;we&rdquo;, &ldquo;us&rdquo;). By
        creating an account or using the service, you agree to these Terms. If
        you do not agree, do not use the service.
      </p>

      <h2>1. The service</h2>
      <p>
        {site.name} is an AI-powered decision-support tool that helps UK
        landlords and letting agents assess prospective tenant applications by
        producing a risk score, summary, and recommendation. It is intended for
        business use within the UK only.
      </p>

      <h2>2. What the service is not</h2>
      <p>
        {site.name} is <strong>not</strong> a credit check, a credit-reference
        agency service, a formal tenant-referencing report, a Right to Rent
        check, or legal advice. Outputs are generated by AI, may contain errors,
        and are provided as an aid to your own judgement. You are solely
        responsible for any letting decision you make.
      </p>

      <h2>3. Eligibility and accounts</h2>
      <p>
        You must be 18 or over and using the service for genuine letting
        purposes. You are responsible for keeping access to your account secure
        and for all activity under it.
      </p>

      <h2>4. Acceptable use</h2>
      <ul>
        <li>
          Only submit applicant data you are lawfully entitled to process, with
          an appropriate lawful basis and privacy notice in place.
        </li>
        <li>
          Do not use the service to discriminate unlawfully or in breach of the
          Equality Act 2010.
        </li>
        <li>
          Do not misuse, reverse-engineer, overload, or attempt to disrupt the
          service.
        </li>
        <li>Do not resell or white-label the service without our agreement.</li>
      </ul>

      <h2>5. Fees and payment</h2>
      <p>
        Screenings are available on a pay-as-you-go basis or through a Pro
        subscription, as set out on our{" "}
        <Link href="/pricing">Pricing page</Link>. Payments are processed by
        Stripe. Credit purchases are consumed as you run screenings.
        Subscriptions renew automatically until cancelled. Except where required
        by law, fees are non-refundable once a screening has been generated.
      </p>

      <h2>6. Your data and ours</h2>
      <p>
        Our handling of personal data is described in our{" "}
        <Link href="/privacy">Privacy Policy</Link>. You retain responsibility
        as controller for the applicant data you submit. We retain ownership of
        the {site.name} software, models, and brand.
      </p>

      <h2>7. Availability</h2>
      <p>
        We aim to keep the service available but do not guarantee uninterrupted
        access. We may modify, suspend, or discontinue features at any time.
      </p>

      <h2>8. Disclaimers</h2>
      <p>
        The service is provided &ldquo;as is&rdquo; and &ldquo;as
        available&rdquo; without warranties of any kind, to the fullest extent
        permitted by law. We do not warrant that outputs are accurate, complete,
        or fit for a particular purpose.
      </p>

      <h2>9. Limitation of liability</h2>
      <p>
        Nothing in these Terms limits liability that cannot be limited by law.
        Subject to that, we are not liable for indirect or consequential loss,
        loss of profit, or losses arising from letting decisions you make. Our
        total liability to you is limited to the fees you paid in the 12 months
        before the event giving rise to the claim.
      </p>

      <h2>10. Termination</h2>
      <p>
        You may stop using the service at any time. We may suspend or terminate
        access if you breach these Terms or use the service unlawfully.
      </p>

      <h2>11. Changes to these Terms</h2>
      <p>
        We may update these Terms from time to time. Continued use after changes
        take effect constitutes acceptance of the updated Terms.
      </p>

      <h2>12. Governing law</h2>
      <p>
        These Terms are governed by the laws of {site.company.registeredIn}, and
        the courts of {site.company.registeredIn} have exclusive jurisdiction.
      </p>

      <h2>13. Contact</h2>
      <p>
        Questions about these Terms? Email{" "}
        <a href={`mailto:${site.email}`}>{site.email}</a> or visit our{" "}
        <Link href="/contact">Contact page</Link>.
      </p>
    </LegalPage>
  );
}
